// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller.js"
application.register("autocomplete", AutocompleteController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import SearchbarController from "./searchbar_controller.js"
application.register("searchbar", SearchbarController)

import ShareModalController from "./share_modal_controller.js"
application.register("share-modal", ShareModalController)

import WishlistController from "./wishlist_controller.js"
application.register("wishlist", WishlistController)
