meta_product_name: "GamingNext"
meta_title: "GamingNext - The perfect game for you"
meta_description: "Your one and only site for finding the right game for you."
meta_image: "cover.png" # should exist in `app/assets/images/`
